[package]
name = "ratex-integration-tests"
version = "0.1.0"
description = "Ratex contract integration tests"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.29.0", features = ["metadata"] }
anchor-client = { version = "0.29.0", features = ["async"] }
bincode = "^1.3.3"
solana-program = "^1.17.18"
solana-program-test = "^1.17.18"
solana-address-lookup-table-program = "^1.17.18"
#klend = { git = "https://github.com/Kamino-Finance/klend.git", package = "kamino_lending", features = ["no-entrypoint"] }
fixed = "1.23.1"
spl-associated-token-account = { version = "1.1.3", features = ["no-entrypoint"] }